name: DEMOAPP
on: 
  push:
     branches: [ master ]
  workflow_dispatch:
env:
  artifact_name: ''
  version-major: '1'
  version-minor: '1'
  version-patch: '1'
  appname: 'demo-app'


jobs: 
  ######################### fixinator_code_scan ####################################
  checkout-Zip-Publish: 
    runs-on: ubuntu-latest
    container:
      image: gradle
      
    steps:
       - name: git download 
         run: |
          apt update
          apt install -y git
 
       - uses: actions/checkout@v3
         with:
             repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}
             token: ${{ secrets.GIT_PAT}}
             ref: ${{ github.REF}}
             fetch-depth: 0 |
             
       - name: setup git config
         run: |
              pwd
              git --version
              git init 
              git config --global  --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
              git config user.name "Github Actions Bot"
              git config user.email "<>"
              
       - name: List Files in Workspace
         run: |
          pwd 
          ls -lrt 
         
       - name: List Changed in files in last commit 
         run: |
          pwd 
          for i in $(git diff HEAD^ HEAD --name-only)
              do
               echo $i
              done
       - name: Create Temp Changed Files Folder 
         run: |
          for i in $(git diff --name-only HEAD~1 -- ':(exclude).github\*' | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | cut -d "/" -f 1 | sort | uniq)
             do 
               echo $i
               mkdir -p ./Release/$i
             done
       - name: List Changedlog Files in Release  Folder 
         run: |
          cd Release
          rm DeployFiles.txt
          touch DeployFiles.txt
          cd ..
          echo "$(git diff HEAD^ HEAD --name-only --diff-filter=ACM ':(exclude).github/*')" > Release/DeployFiles.txt
          cat Release/DeployFiles.txt
          
       - name: Create Temp Changed Files Folder 
         run: |
          for i in $(cat Release/DeployFiles.txt)
             do 
               echo $i
               cp ./$i ./Release/$i
             done
             
             
       - name: Publish Package to Github Registry 
         run: |
             gradle  publish
         env: 
           VERSION: ${{ env.version-major}}.${{ env.version-minor}}.${{ env.version-patch}}.${{ github.run_number}}
           GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
 ################################### DEV Deploy ################################################
  CF_DEV_Deploy: 
    needs: [checkout-Zip-Publish]
    runs-on: WIN_RATIO_1
     #if: ${{ github.event_name != 'push'}}
    
    steps:
       - name: Download artifact from Github Package Registry
         shell: sh
         run: |
           curl -O -L https://_:${{ secrets.GIT_PAT }}@maven.pkg.github.com/${{ github.repository_owner }}/${{github.event.repository.name }}/com/ratio/exchange/TestCICD/${{ env.VERSION}}/TestCICD-${{ env.VERSION}}.zip    
         env: 
           VERSION: ${{ env.version-major}}.${{ env.version-minor}}.${{ env.version-patch}}.${{ github.run_number}}
        
       - name: Unzip Package to temp folder 
         shell: sh
         run: |
           7z x ratio-exchange-${{ env.VERSION}}.zip -otemprelease  
         env: 
           VERSION: ${{ env.version-major}}.${{ env.version-minor}}.${{ env.version-patch}}.${{ github.run_number}}
        
       - name: Copy Extracted Files to Target Server Location 
         run: |
           robocopy "temprelease" "c:\tempccicd\dst" /xf DeployFiles.txt /s
           if ($lastexitcode -lt 8) { exit 0 } else { exit 1 }
         env: 
           VERSION: ${{ env.version-major}}.${{ env.version-minor}}.${{ env.version-patch}}.${{ github.run_number}}
